Fix handling of files without newlines in brp-mangle-shebang
If the file we are trying to mangle a shebang in has
0 lines (as reported by `wc`) `read` command fails
to read the first line and the script fails silently.

Text files without newlines should not be executable as there
is no way for them to contain a shebang.

diff --git a/brp-mangle-shebangs b/brp-mangle-shebangs
--- a/brp-mangle-shebangs
+++ b/brp-mangle-shebangs
@@ -93,7 +93,14 @@ while IFS= read -r line; do
   fi
 
 
-  read shebang_line < "$f"
+  if ! read shebang_line < "$f"; then
+    echo >&2 "*** WARNING: Cannot read the first line from $f, removing executable bit"
+    ts=$(stat -c %y "$f")
+    chmod -x "$f"
+    touch -d "$ts" "$f"
+    continue
+  fi
+
   orig_shebang="${shebang_line#\#!}"
   if [ "$orig_shebang" = "$shebang_line" ]; then
     echo >&2 "*** WARNING: $f is executable but has no shebang, removing executable bit"
